### ISSUE TITLE
Getting Data description is broken

### ISSUE THREAD

**Issue by UkeHa** [projectgoav/E.Deezer#17]
Hi,

the getting data wiki says "var book = result.Result.Data;" but it leads to the following error:

"CS1061 'IBook<IAlbum>' does not contain a definition for 'Data' and no extension method 'Data' accepting a first argument of type 'IBook<IAlbum>' could be found (are you missing a using directive or an assembly reference?) "

**Comment by projectgoav** [comment]
Ops! I've not updated that page for a while. Thanks for pointing it out.

The line should read: 

```
//We have the Data - print the total number of results
var book = result.Result;
Console.WriteLine(book.Total);
```

I've updated the Wiki Page to match.

**Comment by UkeHa** [comment]
"var readTask = book.Read(0, 25);" 

should also be: var readTask = book.Total;

right?

**Comment by projectgoav** [comment]
A Book object total is the total number of items matching your request to the API on Deezer.
To get these items you need to 'read' the book.

So when you search for "Abba", _by default_, get the following JSON response from Deezer:

```
{
  "data": [ 
    {ITEM},
    ....,
    .... ,  //(25 in total)
   ],

  "total": 593,  //<- This is what Book.Total returns.
  "next": "https://api.deezer.com/search/album?q=abba&index=25"
}
```

**book.Total** is equivalent to **"total"**

**book.Read(A, B)** is equivalent to the **"next"** line in the above response, replacing the _index_ parameter with **A** and adding the _limit_ parameter set to **B**

## 

Does this help?
Would it make it easier if I added a description to methods/properties documentation to say exactly what they corrispond to in the API?

**Comment by UkeHa** [comment]
A closer description would be helpful, i guess.

var readTask = book.Read(0, 25); returns 

CS7036  There is no argument given that corresponds to the required formal parameter 'aCallback' of 'IBook<IAlbum>.Read(uint, uint, Action<IPage<IAlbum>>)' for me.

so there needs to be third value of an "album"?

**Comment by projectgoav** [comment]
You should really update E.Deezer to a newer version. Then read is just a task like all other methods. You'll also have more features as well, such as Genre, New Releases and Charts!

## 

I originally had it so that read accepted a 3rd parameter which was a function that would accept the result of the read method.

```
book.Read(0,25, (aResult) => { /* Do Stuff */ });
```

However this was very different from they way the rest of E.Deezer worked with tasks, so I decided to remove that and make read() return a task like all other methods in E.Deezer. 

It's still used internally as the new read is just a wrapper around the old however this old read, requiring a callback, is no longer available to use in later versions of E.Deezer. 

## 

On a side, I have the feeking that my idea of Books, Pages etc may not be the easier for other users to understand. I'm also very bad to documenting so I think over the next week I'll work on similfying the whole process and improving documentation of the whole thing.

**Comment by UkeHa** [comment]
Oh, i've used nuget and must have downloaded an older version there by mistake. Thanks for the heads-up. I've restored it via nuget and now it's working. And using it via a 3rd parameter seems counterintuitive. I'm looking forward to your updates and will try to help where i can.
