### ISSUE TITLE
DeezerSession does not have a "CreateNew()" method

### ISSUE THREAD

**Issue by 420tech** [projectgoav/E.Deezer#92]
I was trying to follow your docs. There is no CreateNew in DeezerSession. So either a doc bug or.....

**Comment by projectgoav** [comment]
Hi there,

The documentation here should apply to 2.X.X.X -> 4.X.X.X verisons of E.Deezer. I've marked the 5.X.X.X packages as pre-release until I have time to complete outstanding work and the accompanying documentation.

I'm assuming that you are using a 5.X.X.X package which is why you aren't seeing a `CreateNew()` method. 

I believe you are wanting something like:
```C#
var httpHandler = new HttpClientHandler(); // Or whatever implementation you want here...
var session = new DeezerSession(httpHandler);

// .. Continue using 'session' to access Deezer API
```

You may find this example app I have written around the library as a helpful reference; https://github.com/projectgoav/E.ExploreDeezer

(DeezerSession is constructed in `E.ExploreDeezer.Core.ServiceRegistry` ctr, Line 38)

**Comment by 420tech** [comment]
Perfect! Thank you!
